### ISSUE TITLE
我尝试修改了 笔趣阁的请求地址，我看了内部的dom结构是一致的 可是为什么我请求不到章节信息 并且书名乱码了 求作者大大看下

### ISSUE THREAD

**Issue by primary-ysj** [aooiuu/z-reader#108]
地址变更为：
const DOMAIN = 'https://www.xxbiqudu.com/';
const DOMAIN2 = 'https://www.xxbiqudu.com/';
新网站查询的url跟之前也是一样的
![image](https://user-images.githubusercontent.com/67618096/212797167-6679e734-77ea-44cd-aa07-c54270bf3c59.png)
章节 还有内容 我看了 dom结构都一样 麻烦大哥有空看看

**Comment by aooiuu** [comment]
刚刚测试的旧域名正常，似乎恢复了

乱码的话，可参考: https://github.com/aooiuu/z-reader/issues/50#issuecomment-903049915

**Comment by primary-ysj** [comment]
大佬 我之前没写过node 你看下我这样写对吗 
![image](https://user-images.githubusercontent.com/67618096/212819560-759d2438-94c6-4cd9-9d06-94e63ba4ecea.png)
![image](https://user-images.githubusercontent.com/67618096/212819590-f06c9463-9f40-4a2e-a092-d18cdc7779c6.png)
我这样 获取不到书名了 这个该怎么调试。。
