### ISSUE TITLE
未联网安装插件后vscode活动栏无图标，无法使用

### ISSUE THREAD

**Issue by chenacgn** [aooiuu/z-reader#112]
未联网环境使用，只想使用本地查看功能，插件安装后无法使用

**Comment by aooiuu** [comment]
可以说下什么版本吗？ 
如果是用离线安装，建议从 [marketplace.visualstudio.com](https://marketplace.visualstudio.com/items?itemName=aooiu.z-reader)  -> `Download Extension` 下载最新的 `.vsix` 安装包安装

安装后侧栏会多一个图标
![image](https://user-images.githubusercontent.com/28108111/226938980-4074093a-c2e6-47f3-8d70-be1c05d6d3e6.png)

**Comment by chenacgn** [comment]
是离线安装，就是在这个市场下载的，安装的是1.1.7版本，安装完后左侧活动栏没有图标




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "aooiuu/z-reader"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月22日(星期三) 晚上10:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [aooiuu/z-reader] 未联网安装插件后vscode活动栏无图标，无法使用 (Issue #112)





 
可以说下什么版本吗？
 如果是用离线安装，建议从 marketplace.visualstudio.com  -&gt; Download Extension 下载最新的 .vsix 安装包安装
 
安装后侧栏会多一个图标

**Comment by chenacgn** [comment]
未联网从visx安装，安装后扩展内看到插件已安装，但是左侧活动栏无图标 无法使用

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月22日(周三) 晚上10:40
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [aooiuu/z-reader] 未联网安装插件后vscode活动栏无图标，无法使用 (Issue #112)




 
可以说下什么版本吗？
 如果是用离线安装，建议从 marketplace.visualstudio.com  -&gt; Download Extension 下载最新的 .vsix 安装包安装
 
安装后侧栏会多一个图标

**Comment by aooiuu** [comment]
1.插件列表看下是否已启用
2.鼠标右键左侧栏看下是否勾选插件
