### ISSUE TITLE
默认配置的笔趣阁源挂了

### ISSUE THREAD

**Issue by RyanZhangLife** [aooiuu/z-reader#116]
我能不能配置新源进去

**Comment by aooiuu** [comment]
版本是 `1.1.10` 吗？前几天更新过

暂时不支持配置源，如果需要可以提PR修改源

**Comment by pilot-c** [comment]
默认配置源上周五挂了，然后发现是笔趣阁的地址变更了。修改\out\reader\driver\biquge\index.js的DOMAIN成新地址的就可以了
