### ISSUE TITLE
读取目录失败

### ISSUE THREAD

**Issue by WXL570CN** [aooiuu/z-reader#118]
建议提供一个配置本地文件目录的功能，现在点击本地报错：读取目录失败, 请检测您的目录设置
目测应该是配置的文件目录找不到，但我又不知道配置的目录在哪。。。

**Comment by WXL570CN** [comment]
找到问题了，少了一个book文件夹

**Comment by laolihaile** [comment]
<img width="846" alt="WeChat7704bdc3001383cf434dbf9db313c218" src="https://github.com/aooiuu/z-reader/assets/46878085/3d17dea3-79a8-49d4-b1de-a66560b02cb7">
已设置目录，依旧提示读取目录失败，请问怎么解决

**Comment by LoveClears** [comment]
> 找到问题了，少了一个书文件夹

找到了吗 在哪设置本地文件夹啊

**Comment by zyt214** [comment]
> <img alt="微信7704bdc3001383cf434dbf9db313c218" width="846" src="https://user-images.githubusercontent.com/46878085/250011062-3d17dea3-79a8-49d4-b1de-a66560b02cb7.png"> 已设置目录，若提示读取目录失败，请问怎么解决

可以设置成绝对路径

**Comment by DuskSwan** [comment]
设置成绝对路径确实管用

**Comment by bluepadu** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://link.bnbreward.online/0mhPJ2)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://link.bnbreward.online/0mhPJ2) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @

**Comment by aooiuu** [comment]
建议迁移到新插件 [any-reader](https://github.com/aooiuu/any-reader)
