### ISSUE TITLE
vip书籍如何阅读

### ISSUE THREAD

**Issue by anglejunn** [aooiuu/z-reader#119]
起点的那些付费章节或者VIP章节怎么读，想登账号没有啊

**Comment by aooiuu** [comment]
https://github.com/aooiuu/z-reader/issues/83

**Comment by MaoFeidu** [comment]
按照设置 我去m.qidian.com登录后在控制台用

document.cookie

抓到了当前使用的cookie,将其添加至setting.json中

    "z-reader.cookies": [
        {
          "url": "https://m.qidian.com",
          "cookie": ""
        }
      ],
然后订阅章节显示

上起点读书APP支持我 还可在评论区与我互动

同上
