### ISSUE TITLE
在线读书笔趣阁的链接似乎不能用了

### ISSUE THREAD

**Issue by linyuanxy** [aooiuu/z-reader#121]

**Comment by linyuanxy** [comment]
用笔趣阁不能搜索了，起点却可以

**Comment by pilot-c** [comment]
亲测成功。修改插件文件夹中的 out\reader\driver\biquge\index.js 的DOMAIN 成最新的网站就可以加载目录搜索等操作了。新网址 --https://www.biquzw.info/。然后保存重新打开VSCode就可以了。

**Comment by linyuanxy** [comment]
谢谢你

**Comment by Apprentice-Howe** [comment]
> 亲测成功。 修改插件文件夹中的 out\reader\driver\biquge\index.js 的DOMAIN 成最新的网站就可以加载目录搜索等操作了。 新网址 --[https://www.biquzw.info/。 然后保存重新打开VSCode就可以了。 ](https://www.biquzw.info/%E3%80%82%E7%84%B6%E5%90%8E%E4%BF%9D%E5%AD%98%E9%87%8D%E6%96%B0%E6%89%93%E5%BC%80VSCode%E5%B0%B1%E5%8F%AF%E4%BB%A5%E4%BA%86%E3%80%82)

好兄弟！

**Comment by linyuanxy** [comment]
加油，摸鱼人

**Comment by aooiuu** [comment]
https://github.com/aooiuu/z-reader/pull/122
