### ISSUE TITLE
错误

### ISSUE THREAD

**Issue by zhou0219** [aooiuu/z-reader#126]
突然一下子搜索不了在线的小说了，插件状态是激活的

**Comment by jy67502** [comment]
最近的更新时间
2023/6/30 16:56:30
更新后，还是不能使用笔趣阁的书源，可以看见目录，但是打不开文件

**Comment by aooiuu** [comment]
源似乎不稳定 直接浏览器刷新网页也会503...

**Comment by aooiuu** [comment]
https://github.com/aooiuu/z-reader/pull/141
