### ISSUE TITLE
笔趣阁的源没办法用了

### ISSUE THREAD

**Issue by MengShaoNian** [aooiuu/z-reader#138]

**Comment by evangelion2010111** [comment]
我也是，用不了
![QQ截图20230816132112](https://github.com/aooiuu/z-reader/assets/118339050/57e6aebd-0432-4b9d-8acc-3ee230682e83)

**Comment by jy67502** [comment]
+1，期望顺便可以把起点源也修复了

**Comment by qianyinghuanmie** [comment]
目前两个源都用不了，希望都修复一下

**Comment by DragonPang14** [comment]
可否增加自己添加源功能

**Comment by WalkAlone0325** [comment]
自己换一下域名，域名变了

**Comment by qianyinghuanmie** [comment]
@WalkAlone0325  域名变成哪个了？

**Comment by pilot-c** [comment]
找到reader的文件夹，我的是.vscode\extensions\aooiu.z-reader-1.1.12\out\reader\driver\biquge文件夹，打开index.js然后将const DOMAIN =“旧源” 换成下面的这个源即可 http://www.xbiquzw.com/

**Comment by qianyinghuanmie** [comment]
@pilot-c 感谢，实测可以，一模一样的操作，可以用了。

**Comment by aooiuu** [comment]
大佬们 来个PR呗

**Comment by pilot-c** [comment]
> 大佬们 来个PR呗

PR了
