### ISSUE TITLE
搜索就网络错误

### ISSUE THREAD

**Issue by myheartwillgoon5** [aooiuu/z-reader#139]

**Comment by myheartwillgoon5** [comment]
网络错误: getaddrinfo ENOENT www.biquzw.info

**Comment by pilot-c** [comment]
找到reader的文件夹，我的是.vscode\extensions\aooiu.z-reader-1.1.12\out\reader\driver\biquge文件夹，打开index.js然后将const DOMAIN =“旧源” 换成下面的这个源即可 http://www.xbiquzw.com/

**Comment by aooiuu** [comment]
https://github.com/aooiuu/z-reader/pull/141
