### ISSUE TITLE
能说下怎么替换源吗？比如，在哪里新增新网站的解析方法。我有空可以改改。ps:因为写后端的，前端一般就jq,vue不太会用

### ISSUE THREAD

**Issue by eatK** [aooiuu/z-reader#140]

**Comment by pilot-c** [comment]
找到reader的文件夹，我的是.vscode\extensions\aooiu.z-reader-1.1.12\out\reader\driver\biquge文件夹，打开index.js然后将const DOMAIN =“旧源” 换成下面的这个源即可 http://www.xbiquzw.com/

**Comment by OYZQ** [comment]
![image](https://github.com/aooiuu/z-reader/assets/46128249/2a4a70c7-6749-483d-ba5b-7a4abc849f34)
修改这里的地址就行

**Comment by eatK** [comment]
重启后搜索报404 ，但是web可以访问该网址，
如图：









原语
***@***.***








期待回复！
&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "aooiuu/z-reader"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月17日(星期四) 下午2:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [aooiuu/z-reader] 能说下怎么替换源吗？比如，在哪里新增新网站的解析方法。我有空可以改改。ps:因为写后端的，前端一般就jq,vue不太会用 (Issue #140)





 

 修改这里的地址就行

**Comment by eatK** [comment]
ok,好了

**Comment by aooiuu** [comment]
> ok,好了

大佬们 来个PR呗

**Comment by aooiuu** [comment]
https://github.com/aooiuu/z-reader/pull/141
