### ISSUE TITLE
会503然后页面消失

### ISSUE THREAD

**Issue by MS-felix** [aooiuu/z-reader#145]
<img width="465" alt="image" src="https://github.com/aooiuu/z-reader/assets/71810098/b38b04e6-e89c-473c-8849-c6817b90135f">

**Comment by andy90s** [comment]
+1

**Comment by HarIki012** [comment]
+1

**Comment by aooiuu** [comment]
固定的书源不稳定， 可以切换新的插件。

https://github.com/aooiuu/z-reader/issues/163

新的插件支持自定义书源。
