### ISSUE TITLE
笔趣阁的源不能用，自己改了一下，发现不能获取目录，能告诉是哪里错了吗

### ISSUE THREAD

**Issue by jy67502** [aooiuu/z-reader#148]
```
"use strict";
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.readerDriver = void 0;
const cheerio = require("cheerio");
const request_1 = require("../../../utils/request");
const TreeNode_1 = require("../../../explorer/TreeNode");
const DOMAIN = 'https://www.yingsx.com';
class ReaderDriver {
    hasChapter() {
        return true;
    }
    search(keyword) {
        return __awaiter(this, void 0, void 0, function* () {
            const result = [];
            try {
                const res = yield request_1.default.send(DOMAIN + '/cse/search?q=' + encodeURI(keyword));
                const $ = cheerio.load(res.body);
                $('.novelslist2 li').each(function (i, elem) {
                    const title =  $(elem).find('span.s2').find('a').text();
                    const author = $(elem).find('span.s4').text();
                    const path =   $(elem).find('span.s2').find('a').attr('href');
                    if (title && author) {
                        result.push(new TreeNode_1.TreeNode(Object.assign({}, TreeNode_1.defaultTreeNode, {
                            type: '.biquge',
                            name: `${title} - ${author}`,
                            isDirectory: true,
                            path
                        })));
                    }
                });
            }
            catch (error) {
                console.warn(error);
            }
            return result;
        });
    }
    getChapter(pathStr) {
        return __awaiter(this, void 0, void 0, function* () {
            const result = [];
            try {
                const res = yield request_1.default.send(DOMAIN + pathStr);
                const $ = cheerio.load(res.body);
                $('#list dd').each(function (i, elem) {
                    const name = $(elem).find('a').text();
                    const path = $(elem).find('a').attr().href;
                    result.push(new TreeNode_1.TreeNode(Object.assign({}, TreeNode_1.defaultTreeNode, {
                        type: '.biquge',
                        name,
                        isDirectory: false,
                        path: pathStr + path
                    })));
                });
            }
            catch (error) {
                console.warn(error);
            }
            return result;
        });
    }
    getContent(pathStr) {
        return __awaiter(this, void 0, void 0, function* () {
            let result = '';
            try {
                const res = yield request_1.default.send(DOMAIN + pathStr);
                const $ = cheerio.load(res.body);
                const html = $('#content').html();
                result = html ? html : '';
            }
            catch (error) {
                console.warn(error);
            }
            return result;
        });
    }
}
exports.readerDriver = new ReaderDriver();
//# sourceMappingURL=index.js.map

```

**Comment by jy67502** [comment]
以前一直以为是是笔趣阁的源挂了，最近才发现是江苏特有 js96110.com.cn给拦截了，难受。现在这段，他可以正确的搜出来书籍，但点开目录就一直转圈，不显示，不知道什么地方错了。

**Comment by jy67502** [comment]
还有，如果可以的话，请问一下，比方说`https://www.shu20.net/`，这种网站是怎么读取的，你如果直接https://www.shu20.net/search/?searchkey=吞噬，这样会403的，但是你在页面里搜索就是没问题的

**Comment by jy67502** [comment]
@pilot-c  大佬可以请教一下吗

**Comment by pilot-c** [comment]
我现在用浏览器打开你的 https://www.shu20.net/ 进行搜索也是403，暂时帮不了你

**Comment by pilot-c** [comment]
> 还有，如果可以的话，请问一下，比方说`https://www.shu20.net/`，这种网站是怎么读取的，你如果直接访问`https://www.shu20.net/search/?searchkey=吞噬`这个链接，这样会403的，但是你在页面里搜索就是没问题的

就按照你上面的思路进行修改就好了。如果是网页正常，请求403的话，估计需要好好看看request的请求头那些。

**Comment by jy67502** [comment]
> > 还有，如果可以的话，请问一下，比方说`https://www.shu20.net/`，这种网站是怎么读取的，你如果直接访问`https://www.shu20.net/search/?searchkey=吞噬`这个链接，这样会403的，但是你在页面里搜索就是没问题的
> 
> 就按照你上面的思路进行修改就好了。如果是网页正常，请求403的话，估计需要好好看看request的请求头那些。

好的，那我想再请教一下。https://www.yingsx.com/5_5858/，这个页面里的，我想请求目录信息，我用#list dd，为什么会得不到目录啊。我看了一下应该是没有问题的，上面传进去的请求路劲也是对的。不知道问题在什么地方

**Comment by pilot-c** [comment]
> > > 还有，如果可以的话，请问一下，比方说`https://www.shu20.net/`，这种网站是怎么读取的，你如果直接访问`https://www.shu20.net/search/?searchkey=吞噬`这个链接，这样会403的，但是你在页面里搜索就是没问题的
> > 
> > 
> > 就按照你上面的思路进行修改就好了。如果是网页正常，请求403的话，估计需要好好看看request的请求头那些。
> 
> 好的，那我想再请教一下。[https://www.yingsx.com/5_5858/，这个页面里的，我想请求目录信息，我用#list](https://www.yingsx.com/5_5858/%EF%BC%8C%E8%BF%99%E4%B8%AA%E9%A1%B5%E9%9D%A2%E9%87%8C%E7%9A%84%EF%BC%8C%E6%88%91%E6%83%B3%E8%AF%B7%E6%B1%82%E7%9B%AE%E5%BD%95%E4%BF%A1%E6%81%AF%EF%BC%8C%E6%88%91%E7%94%A8#list) dd，为什么会得不到目录啊。我看了一下应该是没有问题的，上面传进去的请求路劲也是对的。不知道问题在什么地方
 
我将你的这个https://www.yingsx.com/当 domain，，search那里改了点路径是可以获取到目录的，但是就是获取不到内容，getContent报404。因为我不是做前端开发的，不懂怎么调试这个工程。或者你可以告诉我怎么调试这个工程。

**Comment by jy67502** [comment]
> > > > 还有，如果可以的话，请问一下，比方说`https://www.shu20.net/`，这种网站是怎么读取的，你如果直接访问`https://www.shu20.net/search/?searchkey=吞噬`这个链接，这样会403的，但是你在页面里搜索就是没问题的
> > > 
> > > 
> > > 就按照你上面的思路进行修改就好了。如果是网页正常，请求403的话，估计需要好好看看request的请求头那些。
> > 
> > 
> > 好的，那我想再请教一下。[https://www.yingsx.com/5_5858/，这个页面里的，我想请求目录信息，我用#list](https://www.yingsx.com/5_5858/%EF%BC%8C%E8%BF%99%E4%B8%AA%E9%A1%B5%E9%9D%A2%E9%87%8C%E7%9A%84%EF%BC%8C%E6%88%91%E6%83%B3%E8%AF%B7%E6%B1%82%E7%9B%AE%E5%BD%95%E4%BF%A1%E6%81%AF%EF%BC%8C%E6%88%91%E7%94%A8#list) dd，为什么会得不到目录啊。我看了一下应该是没有问题的，上面传进去的请求路劲也是对的。不知道问题在什么地方
> 
> 我将你的这个[https://www.yingsx.com/当](https://www.yingsx.com/%E5%BD%93) domain，，search那里改了点路径是可以获取到目录的，但是就是获取不到内容，getContent报404。因为我不是做前端开发的，不懂怎么调试这个工程。或者你可以告诉我怎么调试这个工程。

我也是卡在这一步，我把这个工程拉下来后，不知道怎么跑，就只能直接改动插件里的index.js文件。然后发生错误，我就不知道怎么办了。

**Comment by jy67502** [comment]
> > > > 还有，如果可以的话，请问一下，比方说`https://www.shu20.net/`，这种网站是怎么读取的，你如果直接访问`https://www.shu20.net/search/?searchkey=吞噬`这个链接，这样会403的，但是你在页面里搜索就是没问题的
> > > 
> > > 
> > > 就按照你上面的思路进行修改就好了。如果是网页正常，请求403的话，估计需要好好看看request的请求头那些。
> > 
> > 
> > 好的，那我想再请教一下。[https://www.yingsx.com/5_5858/，这个页面里的，我想请求目录信息，我用#list](https://www.yingsx.com/5_5858/%EF%BC%8C%E8%BF%99%E4%B8%AA%E9%A1%B5%E9%9D%A2%E9%87%8C%E7%9A%84%EF%BC%8C%E6%88%91%E6%83%B3%E8%AF%B7%E6%B1%82%E7%9B%AE%E5%BD%95%E4%BF%A1%E6%81%AF%EF%BC%8C%E6%88%91%E7%94%A8#list) dd，为什么会得不到目录啊。我看了一下应该是没有问题的，上面传进去的请求路劲也是对的。不知道问题在什么地方
> 
> 我将你的这个[https://www.yingsx.com/当](https://www.yingsx.com/%E5%BD%93) domain，，search那里改了点路径是可以获取到目录的，但是就是获取不到内容，getContent报404。因为我不是做前端开发的，不懂怎么调试这个工程。或者你可以告诉我怎么调试这个工程。

请问改动了什么，让他获取到了目录啊。我也不会调试这个工程，只能改动插件里index.js文件

**Comment by jy67502** [comment]
@aooiuu 作者大大，可以帮我解决一下上面那段代码的问题吗？因为不知道怎么调试这个工程。
search(keyword)这段应该是改好了的，可以正常显示作品名和作者。返回的path是   /5_5858/
getChapter(pathStr) 这段我就不知道什么地方错了，我点击小说名，他就一直开始转圈圈了

**Comment by pilot-c** [comment]
"use strict";
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.readerDriver = void 0;
const cheerio = require("cheerio");
const request_1 = require("../../../utils/request");
const TreeNode_1 = require("../../../explorer/TreeNode");
const DOMAIN = 'https://www.yingsx.com';
class ReaderDriver {
    hasChapter() {
        return true;
    }
    search(keyword) {
        return __awaiter(this, void 0, void 0, function* () {
            const result = [];
            try {
                const res = yield request_1.default.send(DOMAIN + '/cse/search?q=' + encodeURI(keyword));
                const $ = cheerio.load(res.body);
                $('.novelslist2 li').each(function (i, elem) {
                    const title =  $(elem).find('span.s2').find('a').text();
                    const author = $(elem).find('span.s4').text();
                    const path =   $(elem).find('span.s2').find('a').attr('href');
                    if (title && author) {
                        result.push(new TreeNode_1.TreeNode(Object.assign({}, TreeNode_1.defaultTreeNode, {
                            type: '.biquge',
                            name: `${title} - ${author}`,
                            isDirectory: true,
                            path
                        })));
                    }
                });
            }
            catch (error) {
                console.warn(error);
            }
            return result;
        });
    }
    getChapter(pathStr) {
        return __awaiter(this, void 0, void 0, function* () {
            const result = [];
            try {
                const res = yield request_1.default.send(DOMAIN + pathStr);
                const $ = cheerio.load(res.body);
 	            console.log(pathStr) ;
                $('#list dd').each(function (i, elem) {
                    const name = $(elem).find('a').text();
                    const path = $(elem).find('a').attr().href;
                    result.push(new TreeNode_1.TreeNode(Object.assign({}, TreeNode_1.defaultTreeNode, {
                        type: '.biquge',
                        name,
                        isDirectory: false,
                        path: path
                    })));
                });
            }
            catch (error) {
                console.warn(error);
            }
            return result;
        });
    }
    getContent(pathStr) {
        return __awaiter(this, void 0, void 0, function* () {
            let result = '';
            try {
                const res = yield request_1.default.send(DOMAIN + pathStr);
                const $ = cheerio.load(res.body);
               // const html = $('#content').html().replace("&nbsp;","");
                var html = $('#content').html();
                html=html.replace(RegExp("<br>\n<br>\n", "g"),'<br>\n');
                result = html ? html : '';
            }
            catch (error) {
                console.warn(error);
            }
            return result;
        });
    }
}
exports.readerDriver = new ReaderDriver();
//# sourceMappingURL=index.js.map
//我这样改，是可以获取到章节跟内容了

**Comment by pilot-c** [comment]
"use strict";
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.readerDriver = void 0;
const cheerio = require("cheerio");
const request_1 = require("../../../utils/request");
const TreeNode_1 = require("../../../explorer/TreeNode");
const DOMAIN = 'https://www.yingsx.com'; //修改地方1
class ReaderDriver {
    hasChapter() {
        return true;
    }
    search(keyword) {
        return __awaiter(this, void 0, void 0, function* () {
            const result = [];
            try {
                const res = yield request_1.default.send(DOMAIN + '/cse/search?q=' + encodeURI(keyword)); //修改地方2
                const $ = cheerio.load(res.body);
                $('.novelslist2 li').each(function (i, elem) {
                    const title =  $(elem).find('span.s2').find('a').text();
                    const author = $(elem).find('span.s4').text();
                    const path =   $(elem).find('span.s2').find('a').attr('href');
                    if (title && author) {
                        result.push(new TreeNode_1.TreeNode(Object.assign({}, TreeNode_1.defaultTreeNode, {
                            type: '.biquge',
                            name: `${title} - ${author}`,
                            isDirectory: true,
                            path
                        })));
                    }
                });
            }
            catch (error) {
                console.warn(error);
            }
            return result;
        });
    }
    getChapter(pathStr) {
        return __awaiter(this, void 0, void 0, function* () {
            const result = [];
            try {
                const res = yield request_1.default.send(DOMAIN + pathStr);
                const $ = cheerio.load(res.body);
 	            console.log(pathStr) ;
                $('#list dd').each(function (i, elem) {
                    const name = $(elem).find('a').text();
                    const path = $(elem).find('a').attr().href;
                    result.push(new TreeNode_1.TreeNode(Object.assign({}, TreeNode_1.defaultTreeNode, {
                        type: '.biquge',
                        name,
                        isDirectory: false,
                        path: path //修改地方3
                    })));
                });
            }
            catch (error) {
                console.warn(error);
            }
            return result;
        });
    }
    getContent(pathStr) {
        return __awaiter(this, void 0, void 0, function* () {
            let result = '';
            try {
                const res = yield request_1.default.send(DOMAIN + pathStr);
                const $ = cheerio.load(res.body);
               // const html = $('#content').html();//修改地方4
                var html = $('#content').html();//修改地方4
                html=html.replace(RegExp("<br>\n<br>\n", "g"),'<br>\n');//修改地方5
                result = html ? html : '';
            }
            catch (error) {
                console.warn(error);
            }
            return result;
        });
    }
}
exports.readerDriver = new ReaderDriver();
//# sourceMappingURL=index.js.map
![image](https://github.com/aooiuu/z-reader/assets/17928124/b952a9e3-d99e-4c07-8236-f57b596a38f1)

**Comment by pilot-c** [comment]
"use strict";
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.readerDriver = void 0;
const cheerio = require("cheerio");
const request_1 = require("../../../utils/request");
const TreeNode_1 = require("../../../explorer/TreeNode");
const DOMAIN = 'https://www.yingsx.com'; //修改地方1
class ReaderDriver {
    hasChapter() {
        return true;
    }
    search(keyword) {
        return __awaiter(this, void 0, void 0, function* () {
            const result = [];
            try {
                const res = yield request_1.default.send(DOMAIN + '/cse/search?q=' + encodeURI(keyword)); //修改地方2
                const $ = cheerio.load(res.body);
                $('.novelslist2 li').each(function (i, elem) {
                    const title =  $(elem).find('span.s2').find('a').text();
                    const author = $(elem).find('span.s4').text();
                    const path =   $(elem).find('span.s2').find('a').attr('href');
                    if (title && author) {
                        result.push(new TreeNode_1.TreeNode(Object.assign({}, TreeNode_1.defaultTreeNode, {
                            type: '.biquge',
                            name: `${title} - ${author}`,
                            isDirectory: true,
                            path
                        })));
                    }
                });
            }
            catch (error) {
                console.warn(error);
            }
            return result;
        });
    }
    getChapter(pathStr) {
        return __awaiter(this, void 0, void 0, function* () {
            const result = [];
            try {
                const res = yield request_1.default.send(DOMAIN + pathStr);
                const $ = cheerio.load(res.body);
 	            console.log(pathStr) ;
                $('#list dd').each(function (i, elem) {
                    const name = $(elem).find('a').text();
                    const path = $(elem).find('a').attr().href;
                    result.push(new TreeNode_1.TreeNode(Object.assign({}, TreeNode_1.defaultTreeNode, {
                        type: '.biquge',
                        name,
                        isDirectory: false,
                        path: path //修改地方3
                    })));
                });
            }
            catch (error) {
                console.warn(error);
            }
            return result;
        });
    }
    getContent(pathStr) {
        return __awaiter(this, void 0, void 0, function* () {
            let result = '';
            try {
                const res = yield request_1.default.send(DOMAIN + pathStr);
                const $ = cheerio.load(res.body);
               // const html = $('#content').html();//修改地方4
                var html = $('#content').html();//修改地方4
                html=html.replace(RegExp("<br>\n<br>\n", "g"),'<br>\n');//修改地方5
                result = html ? html : '';
            }
            catch (error) {
                console.warn(error);
            }
            return result;
        });
    }
}
exports.readerDriver = new ReaderDriver();
//# sourceMappingURL=index.js.map
![image](https://github.com/aooiuu/z-reader/assets/17928124/ced30d96-6400-4ed0-bfa6-717e4bc0aeb8)
调试过，是可以获取到你说的这个网址下的目录，子目录，内容的

**Comment by jy67502** [comment]
@pilot-c  十分感谢

**Comment by aooiuu** [comment]
> 怎么调试这个工程

理论上下载代码然后直接按`F5`就可以进行调试了
