### ISSUE TITLE
笔趣阁这个网站搜索有问题，书搜索不出来

### ISSUE THREAD

**Issue by linyuanxy** [aooiuu/z-reader#149]
搜不出来

**Comment by Orange-dark** [comment]
我也发现了这个问题，应该是那个源已经出问题，可以把源换成这个也许 https://www.xbiquge.bz

**Comment by whyds000** [comment]
@Orange-dark  老铁，怎么切换源，我看只能选笔趣阁和起点

**Comment by Orange-dark** [comment]
> @Orange-dark 老铁，怎么切换源，我看只能选笔趣阁和起点

除非作者更新，不然的话你就只能自己改源码然后本地打包自己做个插件使用

**Comment by whyds000** [comment]
@Orange-dark  好的，感谢

**Comment by 15669623626** [comment]
换成https://www.beqege.com这个源也可以，速度也不错

**Comment by aooiuu** [comment]
固定的书源不稳定， 可以切换新的插件。

https://github.com/aooiuu/z-reader/issues/163

新的插件支持自定义书源。
