### ISSUE TITLE
index.html路径错误，导致打不开任何电子书

### ISSUE THREAD

**Issue by Clark-G** [aooiuu/z-reader#15]
<img width="1342" alt="zreader" src="https://user-images.githubusercontent.com/16334815/84233542-1dc7e280-ab25-11ea-8528-7cc0a68395a2.png">
如上图所示，不知道怎么回事后面的路径都成了反斜杠了，我用的是mac

**Comment by aooiuu** [comment]
修改了一下，但是我这边没测试，如果还不行麻烦告知，我再改。

**Comment by Clark-G** [comment]
> 修改了一下，但是我这边没测试，如果还不行麻烦告知，我再改。

刚才试了一下，没问题了，可以打开了
