### ISSUE TITLE
打开本地文件目录失效

### ISSUE THREAD

**Issue by TomHe789** [aooiuu/z-reader#152]
本地文件目录菜单点击失效
![image](https://github.com/aooiuu/z-reader/assets/50691746/00f0727f-c086-4369-94fe-3dbf5bee8cd8)

**Comment by nikiwo** [comment]
![企业微信截图_17011441397729](https://github.com/aooiuu/z-reader/assets/61222647/09eb4cd9-418e-47da-aad5-5aaa6d64e74a)
我在這新增一個book的文件夾就可以用了

**Comment by TomHe789** [comment]
新增book文件夹就ok了，谢谢
