### ISSUE TITLE
几天以前能搜到的小说，现在搜索不到了

### ISSUE THREAD

**Issue by superlovetomato** [aooiuu/z-reader#159]
小说源：笔趣阁

书名：红楼春

问题：几天前我还能搜到这本书的，今天我搜不到了，我想问下，是代码更新后的问题？还是网站源的问题？

**Comment by aooiuu** [comment]
站源。 

一般这种情况浏览器直接输入网址也打不开

**Comment by aooiuu** [comment]
年后会更新。新版本会支持自定义源
