### ISSUE TITLE
阅读进度保存后没有自动跳转

### ISSUE THREAD

**Issue by web-mobli** [aooiuu/z-reader#166]
正常阅读进度自动保存
![image](https://github.com/aooiuu/z-reader/assets/87005541/5ca703d5-e814-4184-9482-70876c2666d3)

关闭后重新打开，状态栏进度为之前保存的，但是页面阅读位置并没有跳转还是在最顶部
![image](https://github.com/aooiuu/z-reader/assets/87005541/1942de86-fb6d-44b4-89c5-806b73ab0fc5)

**Comment by aooiuu** [comment]
https://github.com/aooiuu/any-reader

建议使用新插件。新插件有这个功能
