### ISSUE TITLE
希望能改变小说字体和大小

### ISSUE THREAD

**Issue by haoisli9** [aooiuu/z-reader#19]
每次打开小说字体都太小，放大后字体和大小都保存不下来；希望能增加可调整小说字体和大小的功能，谢谢

**Comment by diveDylan** [comment]
1

**Comment by aooiuu** [comment]
> 每次打开小说字体都太小，放大后字体和大小都保存不下来；希望能增加可调整小说字体和大小的功能，谢谢

自己写css或者js都行, 打开阅读页->鼠标右键弹出菜单->样式编辑

**Comment by Mebiusbear** [comment]
进去模版那里"extensions/aooiu.z-reader-1.1.7/static/template/defaul/index.html"
把<div class="content" style="font-size: 16px">{{ content }}</div>改为<div class="content" >{{ content }}</div>
然后去css那里.content加上font-size : ?px;即可
