### ISSUE TITLE
可以考虑自由管理搜索来源的网站嘛

### ISSUE THREAD

**Issue by threethreenine** [aooiuu/z-reader#23]
希望搜索来源可以手动设置

**Comment by G-eFan** [comment]
代码一共也没几行。。。

**Comment by hjhdsg** [comment]
看代码是把网页内容爬取下来的,每个网站的结构不一样,手动设置搜索来源这个应该很难实现,爬下来的网页内容解析方式肯定跟已有的不一样

**Comment by aooiuu** [comment]
固定的书源不稳定， 可以切换新的插件。

https://github.com/aooiuu/z-reader/issues/163

新的插件支持自定义书源。
