### ISSUE TITLE
问题：

### ISSUE THREAD

**Issue by bighanhjk** [aooiuu/z-reader#3]
1，右下角总会出现很多消息
2，目录的拉取有待优化，目前会把图片页拉出来
3，无法显示图片
4，会出现很多莫名奇妙的空行，严重影响阅读
建议增加改变字体颜色和大小的功能

**Comment by aooiuu** [comment]
谢谢你的反馈,我会尽快修正部分功能.

增加改变字体颜色和大小的功能: 可以鼠标右键->编辑CSS,另外字体放大缩小和vscode自身是一样的,在html里有写JS事件

**Comment by Discreater** [comment]
目前还没有图片支持吗

**Comment by cliuyang** [comment]
希望增加图片的支持，会方便很多。

**Comment by jseanj** [comment]
希望增加图片支持
