### ISSUE TITLE
现在使用笔趣阁搜索不到任何电子书，可否增加配置供使用者选择/更改搜索来源呢？

### ISSUE THREAD

**Issue by G-MX** [aooiuu/z-reader#43]

**Comment by wangying8016** [comment]
+1

**Comment by SolitaryCity** [comment]
/out/reader/driver/biquge/index.js 中的 const DOMAIN = 'https://m.sobiquge.com';
这是目前最快的方法

**Comment by liuxing95** [comment]
> /out/reader/driver/biquge/index.js 中
> const DOMAIN = 'https://www.sobiquge.com'; //改
> const DOMAIN2 = 'https://m.sobiquge.com'; //添加
> 然后把搜索 search 方法中的 DOMAIN 改成 DOMAIN2
> 
> 这是目前最快的方法

你这个是要在在哪操作的 我这 /目录下 没有 out文件夹

**Comment by G-MX** [comment]
> > /out/reader/driver/biquge/index.js 中
> > const DOMAIN = 'https://www.sobiquge.com'; //改
> > const DOMAIN2 = 'https://m.sobiquge.com'; //添加
> > 然后把搜索 search 方法中的 DOMAIN 改成 DOMAIN2
> > 这是目前最快的方法
> 
> 你这个是要在在哪操作的 我这 /目录下 没有 out文件夹

找找你电脑里面vscode安装的插件在哪个路径下面，任何进去说的这个文件里面修改这个网址参数再重启一下vscode就行了

**Comment by SolitaryCity** [comment]
> > /out/reader/driver/biquge/index.js 中
> > const DOMAIN = ' https://www.sobiquge.com '; //改
> > const DOMAIN2 = ' https://m.sobiquge.com '; //添加
> > 然后把搜索搜索方法中的DOMAIN改成DOMAIN2
> > 这是当前可能的方法
> 
> 你是要在哪一个操作的我这/目录下没有这个文件夹

就vscode安装插件位置中对应的插件下面的   
在插件本地在线 旁边有三个点里面有个 打开本地文件目录 这是比较快找的对应路径的方法

**Comment by G-MX** [comment]
> /out/reader/driver/biquge/index.js 中
> const DOMAIN = 'https://www.sobiquge.com'; //改
> const DOMAIN2 = 'https://m.sobiquge.com'; //添加
> 然后把搜索 search 方法中的 DOMAIN 改成 DOMAIN2
> 
> 这是目前最快的方法



> /out/reader/driver/biquge/index.js 中
> const DOMAIN = 'https://www.sobiquge.com'; //改
> const DOMAIN2 = 'https://m.sobiquge.com'; //添加
> 然后把搜索 search 方法中的 DOMAIN 改成 DOMAIN2
> 
> 这是目前最快的方法

请问DOMAIN2这个参数能修改成其他的网址吗，这个新的网址能搜索到书名，但是加载不出来章节，这种有什么办法解决吗

**Comment by SolitaryCity** [comment]
> > /out/reader/driver/biquge/index.js 中
> > const DOMAIN = 'https://www.sobiquge.com'; //改
> > const DOMAIN2 = 'https://m.sobiquge.com'; //添加
> > 然后把搜索 search 方法中的 DOMAIN 改成 DOMAIN2
> > 这是目前最快的方法
> 
> > /out/reader/driver/biquge/index.js 中
> > const DOMAIN = 'https://www.sobiquge.com'; //改
> > const DOMAIN2 = 'https://m.sobiquge.com'; //添加
> > 然后把搜索 search 方法中的 DOMAIN 改成 DOMAIN2
> > 这是目前最快的方法
> 
> 请问DOMAIN2这个参数能修改成其他的网址吗，这个新的网址能搜索到书名，但是加载不出来章节，这种有什么办法解决吗

getChapter 这个方法是获取章节的 具体要看请求链接返回的东西 
#list dd 是获取章节名称 链接等外面的节点的class名称
name 是获取的 章节名称
path 是链接

getContent 是获取章节内容
请求返回结果 返回的是html 

具体可以仔细看下代码 这个代码不是特别复杂 看代码就能看出其大概的用途 可以在他原有的代码上扩展出新的 搜索源

**Comment by leslie-gl** [comment]
我做了一下修改，下载解压安装即可
https://wwr.lanzoui.com/iv0Tgqufgxa
密码:f1d5

**Comment by bill-mark** [comment]
> 我做了一下修改，下载解压安装即可
> https://wwr.lanzoui.com/iv0Tgqufgxa
> 密码:f1d5

大神666啊 验证可以

**Comment by jiangyiba** [comment]
> > 我做了一下修改，下载解压安装即可
> > https://wwr.lanzoui.com/iv0Tgqufgxa
> > 密码:f1d5
> 
> 大神666啊 验证可以

我用了，还是不行

**Comment by bill-mark** [comment]
> > > 我做了一下修改，下载解压安装即可
> > > https://wwr.lanzoui.com/iv0Tgqufgxa
> > > 密码:f1d5
> > 
> > 
> > 大神666啊 验证可以
> 
> 我用了，还是不行

我刚刚用 又不行了

**Comment by Vacny** [comment]
修改后的网站有点不稳定

**Comment by leslie-gl** [comment]
> > > > 我做了一下修改，下载解压安装即可
> > > > https://wwr.lanzoui.com/iv0Tgqufgxa
> > > > 密码:f1d5
> > > 
> > > 
> > > 大神666啊 验证可以
> > 
> > 
> > 我用了，还是不行
> 
> 我刚刚用 又不行了
 
**最新调整：**

  目前在线书源共支持四个：
  - 起点
  - 笔趣阁： https://www.xxbiquge.net
  - 新笔趣阁：https://www.xbiquge.la
  - 八一中文：https://www.81xs.cc

下载地址：https://wwr.lanzoui.com/b02c7a2sh 密码:8882

**Comment by Dreamerzq** [comment]
> > > > > 我稍微修改一下，下载解压安装分类
> > > > > [https://wwr.lanzoui.c​​om/iv0Tgqufgxa](https://wwr.lanzoui.com/iv0Tgqufgxa)
> > > > > 密码：f1d5
> > > > 
> > > > 
> > > > 大神666啊验证可以
> > > 
> > > 
> > > 我用了，还是不行
> > 
> > 
> > 我只能用又不能了
> 
> **最新调整：**
> 
> 当前在线书源共支持四：
> 
> * 起点
> * 笔趣阁：https://www.xxbiquge.net
> * 新笔趣阁：https://www.xbiquge.la
> * 八一中文：https://www.81xs.cc
> 
> 下载地址：[https://wwr.lanzoui.c​​om/b02c7a2sh](https://wwr.lanzoui.com/b02c7a2sh)密码：8882

请问怎么安装？

**Comment by Dreamerzq** [comment]
> > > > > 我做了一下修改，下载解压安装即可
> > > > > https://wwr.lanzoui.com/iv0Tgqufgxa
> > > > > 密码:f1d5
> > > > 
> > > > 
> > > > 大神666啊 验证可以
> > > 
> > > 
> > > 我用了，还是不行
> > 
> > 
> > 我刚刚用 又不行了
> 
> **最新调整：**
> 
> 目前在线书源共支持四个：
> 
> * 起点
> * 笔趣阁： https://www.xxbiquge.net
> * 新笔趣阁：https://www.xbiquge.la
> * 八一中文：https://www.81xs.cc
> 
> 下载地址：https://wwr.lanzoui.com/b02c7a2sh 密码:8882

安装好了，可以使用，谢谢大神

**Comment by kefeibuhuifei** [comment]
现在怎么都是404了？

**Comment by idea-zone** [comment]
我今天试了下，用 const DOMAIN2 = ' https://m.sobiquge.com '; //添加 的话，可以获取到书籍，但无法获取到目录。调试发现 getChapter 中获取的内容如下，如何通过 `<link…ook/51202/` 获取实际上网页对应的内容:
~~~html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<title>我家娘子不是妖无弹窗_极品豆芽_我家娘子不是妖最新章节列表_笔趣阁移动版</title>
<meta name="keywords" content="我家娘子不是妖,我家娘子不是妖无弹窗" />
<meta name="description" content="我家娘子不是妖无弹窗最新章节由网友提供，《我家娘子不是妖》情节跌宕起伏、扣人心弦，是一本情节与文笔俱佳的玄幻小说，笔趣阁免费提供我家娘子不是妖最新清爽干净的文字章节在线阅读。" />
<meta name="MobileOptimized" content="240"/>
<meta name="applicable-device" content="mobile"/>
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0" />
<link…ook/51202/",
 	"appid": "",
	"title": "我家娘子不是妖无弹窗_极品豆芽_我家娘子不是妖最新章节列表_笔趣阁移动版",
	"images": ["https://www.sobiquge.com/files/article/image/51/51202/51202s.jpg"],
	"description": "天降美娇妻，坐拥万贯财。因为一纸神秘婚书，本是一介小捕头的陈牧莫名多了一位漂亮媳妇，以及万贯家财。媳妇姓白，美若天仙。身边还有一位叫小青的娇媚丫鬟。然而某天，一个浑身刺有金龙纹身的和尚忽然找到他，并告诉了他一个惊天大秘密——“施主，你家娘子不是人，她……是妖！”最让陈牧无语的是，不知从哪儿还冒出了七个头顶葫芦的精神小伙，声称媳妇抓了他们的爷爷。一时间，陈牧彻底凌乱了……——这是一个妖魍横行的世界，也是一个极欲极恶的世界。（豆芽出品，必属精品！）",
	"pubDate": "2021-02-24T12:38:31",
	"upDate": "2021-09-25T11:49:03"
}</script>
</body>
</html>
~~~
