### ISSUE TITLE
笔趣阁原来的网站搜索找不到了

### ISSUE THREAD

**Issue by yanlunhui** [aooiuu/z-reader#46]
// const DOMAIN = 'https://www.biquge.com.cn';
const DOMAIN = 'https://www.xbiquge.la/';
// https://www.xbiquge.la/modules/article/waps.php
class ReaderDriver {
    hasChapter() {
        return true;
    }
    search(keyword) {
        return __awaiter(this, void 0, void 0, function* () {
            const result = [];
            try {
                // const res = yield got(DOMAIN + '/search.php?q=' + encodeURI(keyword));
                const res = yield got(DOMAIN + '/modules/article/waps.php?searchkey=' + encodeURI(keyword))
                const $ = cheerio.load(res.body);
                $('.grid tr').each(function (i, elem) {
                    const title = $($(elem).find('td')[0]).text();
                    const author = $($(elem).find('td')[2]).text();
                    const path = $($(elem).find('td')[0]).find('a').length > 0 ? $($(elem).find('td')[0]).find('a').attr().href : '';
                    result.push(new TreeNode_1.TreeNode(Object.assign({}, TreeNode_1.defaultProblem, {
                        type: '.biquge',
                        name: `${title} - ${author}`,
                        isDirectory: true,
                        path
                    })));
                });
            }
            catch (error) {
                console.warn(error);
            }
            return result;
        });
    }

**Comment by yanlunhui** [comment]
\aooiu.z-reader-1.0.3\out\reader\driver\biquge\index.js 文件

**Comment by yanlunhui** [comment]
"use strict";
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
Object.defineProperty(exports, "__esModule", { value: true });
const got = require("got");
const cheerio = require("cheerio");
const TreeNode_1 = require("../../../explorer/TreeNode");
// const DOMAIN = 'https://www.biquge.com.cn';
const DOMAIN = 'https://www.xbiquge.la/';
// https://www.xbiquge.la/modules/article/waps.php
class ReaderDriver {
    hasChapter() {
        return true;
    }
    search(keyword) {
        return __awaiter(this, void 0, void 0, function* () {
            const result = [];
            try {
                // const res = yield got(DOMAIN + '/search.php?q=' + encodeURI(keyword));
                const res = yield got(DOMAIN + '/modules/article/waps.php?searchkey=' + encodeURI(keyword))
                const $ = cheerio.load(res.body);
                $('.grid tr').each(function (i, elem) {
                    const title = $($(elem).find('td')[0]).text();
                    const author = $($(elem).find('td')[2]).text();
                    const path = $($(elem).find('td')[0]).find('a').length > 0 ? $($(elem).find('td')[0]).find('a').attr().href : '';
                    result.push(new TreeNode_1.TreeNode(Object.assign({}, TreeNode_1.defaultProblem, {
                        type: '.biquge',
                        name: `${title} - ${author}`,
                        isDirectory: true,
                        path
                    })));
                });
            }
            catch (error) {
                console.warn(error);
            }
            return result;
        });
    }
    getChapter(pathStr) {
        return __awaiter(this, void 0, void 0, function* () {
            const result = [];
            try {
                console.log(pathStr)
                const res = yield got(pathStr);
                const $ = cheerio.load(res.body);
                $('#list dd').each(function (i, elem) {
                    // console.log(elem)
                    const name = $(elem).find('a').text();
                    // console.
                    const path = $(elem).find('a').attr().href;
                    result.push(new TreeNode_1.TreeNode(Object.assign({}, TreeNode_1.defaultProblem, {
                        type: '.biquge',
                        name,
                        isDirectory: false,
                        path
                    })));
                });
            }
            catch (error) {
                console.warn(error);
            }
            return result;
        });
    }
    getContent(pathStr) {
        return __awaiter(this, void 0, void 0, function* () {
            let result = '';
            try {
                console.log(pathStr)
                const res = yield got(DOMAIN + pathStr);
                const $ = cheerio.load(res.body);
                const html = $('#content').html();
                result = html ? html : '';
            }
            catch (error) {
                console.warn(error);
            }
            return result;
        });
    }
}
exports.readerDriver = new ReaderDriver();
//# sourceMappingURL=index.js.map

**Comment by xuwhao** [comment]
这样替换之后可以搜到书了 但是看不到章节 getChapter方法也要修改下 点赞先
