### ISSUE TITLE
Iconv-lite warning: decode()-ing strings is deprecated

### ISSUE THREAD

**Issue by ModeSpr** [aooiuu/z-reader#55]
v1.0.6版本【八一】等源报错：
`Iconv-lite warning: decode()-ing strings is deprecated. Refer to https://github.com/ashtuchkin/iconv-lite/wiki/Use-Buffers-when-decoding`

**Comment by aooiuu** [comment]
- - v1.0.6版本 我还没有内置【八一】源呢， 所以我也不知道你这错误哪里来的

**Comment by ModeSpr** [comment]
看明白了，got要加`{encoding:null}`，然后再解码，解码要看网页编码是`gbk`还是`gb2312`

**Comment by aooiuu** [comment]
GBK之类的加 `{encoding:null}`, UTF8不用加， 因为UTF8不用转码了，  `{encoding:null}` 是为了转码的
