### ISSUE TITLE
在 wsl 下，打不开内容

### ISSUE THREAD

**Issue by 377960738** [aooiuu/z-reader#63]
### 首先说明，我是在 **_wsl_** 下打开的vscode

下图是出现问题的版本：
![image](https://user-images.githubusercontent.com/25890436/139770066-6213e1e3-9bec-4ed1-9a44-a07365779f6f.png)

下面这个是报错的信息：
![image](https://user-images.githubusercontent.com/25890436/139770164-3e560609-33e6-4017-9825-ce621d05c273.png)
![image](https://user-images.githubusercontent.com/25890436/139770632-9b33d599-5660-4605-8be0-52b74a505305.png)

**Comment by aooiuu** [comment]
谢谢反馈，不是大佬。 1.1.3版本应该修复了
