### ISSUE TITLE
提一点点建议

### ISSUE THREAD

**Issue by kgdfj** [aooiuu/z-reader#64]
1. background、color、font-size 做成vscode配置项，不然每次更新都要重新编辑页面和style.css
2. 作为一个摸鱼插件，建议将标题改为 README.md，或者也做成一个vscode配置项

**Comment by aooiuu** [comment]
第二点已经有配置项支持了, 打开设置，搜索 `z-reader.readerViewTitle`, 改成任意的文本就可以了

**Comment by TiAmo-he** [comment]
笔趣阁渠道所配置的网站是哪一个啊，东西好少，我试了一下完美世界，大主宰都没有，阁子那么多，建议多配置几个阁子渠道丰富一下，我手机版阁子能看的小说这个搜不到。

**Comment by hjhdsg** [comment]
@TiAmo-he 好像是http://www.biquge.com.cn/

**Comment by hjhdsg** [comment]
https://www.sobiquge.com @TiAmo-he
