### ISSUE TITLE
笔趣阁搜索后无响应

### ISSUE THREAD

**Issue by iamjing66** [aooiuu/z-reader#66]
选择`笔趣阁`后搜索书名`芝加哥1990`等都无法加载列表，无响应 @aooiuu

**Comment by iamjing66** [comment]
版本 1.1.3

**Comment by ppxiagogo** [comment]
同样,笔趣阁搜索无响应，起点可以，网络正常，可以访问笔趣阁，版本1.1.3,重启重装都无法解决问题，
还有个疑问，那么多笔趣阁，使用的是哪个呢,

**Comment by ppxiagogo** [comment]
搜索什么书名都搜不到，搞半天是这个源的 https://www.sobiquge.com 搜索页崩了，403了，擦

**Comment by iamjing66** [comment]
> 搜索什么书名都搜不到，搞半天是这个源的 https://www.sobiquge.com 搜索页崩了，403了，擦

这个源首页可以点，但是搜索直接403，换了其他源可能是解析不对也没法看

**Comment by ppxiagogo** [comment]
现在可以看了   这个源没好  但是能搜索出来了
