### ISSUE TITLE
本地的txt的打开,白屏

### ISSUE THREAD

**Issue by mwei0321** [aooiuu/z-reader#70]
本地的txt的打开,白屏,
一直无法打开

**Comment by xuyichenmo** [comment]
+1

**Comment by xuyichenmo** [comment]
> +1

这个问题主要是由于txt太大，加载时间比较长的原因，希望增加分隔txt

**Comment by shaoyahu** [comment]
求教如何打开本地的,我下载了txt不知道如何用该插件打开,点击本地显示一片空的

**Comment by SadBoen** [comment]
作者的意思是，你们这些渣渣，就是不鸟你们！看不起你们！

**Comment by aooiuu** [comment]
> 

需要先打开设置 搜索 `z-reader.fileDir` 设置下目录。然后插件就会加载本地文件了

**Comment by aooiuu** [comment]
> 求教如何打开本地的,我下载了txt不知道如何用该插件打开,点击本地显示一片空的

需要先打开设置 搜索 `z-reader.fileDir`  设置下目录。然后插件就会加载本地文件了
