### ISSUE TITLE
刚下载完，就不能点击本地目录，搜索书籍也没反应

### ISSUE THREAD

**Issue by FZS999** [aooiuu/z-reader#74]
不知道是我vscode的版本问题还是啥问题反正都是不能用

**Comment by FZS999** [comment]
![image](https://user-images.githubusercontent.com/57242117/153375039-0807acfe-7f85-4a2c-b99a-07a17e9b3440.png)

**Comment by FZS999** [comment]
点击本地后结果就是上面那个图，在线搜索的话搜索完就没反应了

**Comment by FZS999** [comment]
本地的话解决了
![image](https://user-images.githubusercontent.com/57242117/153377465-9723e698-bbcb-4410-8fe5-bfb97ceab992.png)
![Uploading image.png…]()

**Comment by FZS999** [comment]
笔趣阁和起点都搜索不到

**Comment by FZS999** [comment]
我电脑的kaf-cli.exe这个也打不开
![image](https://user-images.githubusercontent.com/57242117/153789712-6955c2e8-2744-4b8b-a8b1-0b312ea32c05.png)

**Comment by aooiuu** [comment]
> 笔趣阁和起点都搜索不到

建议看看官网能不能打开呢？

**Comment by aooiuu** [comment]
> 我电脑的kaf-cli.exe这个也打不开 ![image](https://user-images.githubusercontent.com/57242117/153789712-6955c2e8-2744-4b8b-a8b1-0b312ea32c05.png)


这种情况可能是下载的文件不对，要根据自己设备的系统架构下载

**Comment by FZS999** [comment]
官网是可以打开的
![image](https://user-images.githubusercontent.com/57242117/153806442-4a626061-f056-4350-b7c3-4dc1678cd62a.png)

**Comment by FZS999** [comment]
这个是我搜索后面就是这样一个都没有，总感觉是我电脑的什么配置之类的有问题，我上面有一个摸鱼派的也登录不进去，然后别人的就没问题

**Comment by aooiuu** [comment]
https://m.qidian.com/  浏览器能打开不 ?

**Comment by FZS999** [comment]
可以

**Comment by FZS999** [comment]
管网都能打开

**Comment by FZS999** [comment]
这个用什么浏览器打开应该没限制吧

**Comment by aooiuu** [comment]
> 管网都能打开

![image](https://user-images.githubusercontent.com/28108111/153806916-4f045c66-3a6f-4ba2-af15-8cc02303e806.png)


源选择的是起点吗？

**Comment by FZS999** [comment]
2个都有试过

**Comment by aooiuu** [comment]
> 2个都有试过

那没可能没办法了 超出我的认知范围 可以自己下载源码debug看看....

**Comment by FZS999** [comment]
好的，这个安装完应该不用去配置什么东西就可以搜索吧

**Comment by aooiuu** [comment]
> 好的，这个安装完应该不用去配置什么东西就可以搜索吧

是的
