### ISSUE TITLE
笔趣阁源现在没有数据了，是站点换了吗，还可以问一下怎么使用本地阅读功能

### ISSUE THREAD

**Issue by tanchang123** [aooiuu/z-reader#78]
笔趣阁源现在没有数据了，是站点换了吗，还可以问一下怎么使用本地阅读功能
@aooiuu

**Comment by aooiuu** [comment]
怎么使用本地阅读功能:
1. vscode 打开设置，搜索 `z-reader`, 里面有一个 `本地小说目录` 的配置，改成存放小说的文件夹路径
