### ISSUE TITLE
挂了 搜索不到

### ISSUE THREAD

**Issue by Power-kxLee** [aooiuu/z-reader#80]
挂了 搜索不到

**Comment by maginapp** [comment]
以笔趣阁为例
1. 拉代码，安装依赖 yanr
2. 修改本地请求地址 z-reader/src/reader/driver/biquge/index.ts，访问笔趣阁官网获取
3. 本地编译 yarn run build
4. 安装本地打包生成的vslx文件

**Comment by BaoXianSheng** [comment]
> 以笔趣阁为例
> 
> 1. 拉代码，安装依赖 yanr
> 2. 修改本地请求地址 z-reader/src/reader/driver/biquge/index.ts，访问笔趣阁官网获取
> 3. 本地编译 yarn run build
> 4. 安装本地打包生成的vslx文件

The engine "vscode" appears to be invalid

> 以笔趣阁为例
> 
> 1. 拉代码，安装依赖 yanr
> 2. 修改本地请求地址 z-reader/src/reader/driver/biquge/index.ts，访问笔趣阁官网获取
> 3. 本地编译 yarn run build
> 4. 安装本地打包生成的vslx文件

![image](https://user-images.githubusercontent.com/23521135/170216787-56ae6dc7-49ee-4066-988f-73cc829eb30f.png)
这怎么解决啊

**Comment by aooiuu** [comment]
> > 以笔趣阁为例
> > 
> > 1. 拉代码，安装依赖 yanr
> > 2. 修改本地请求地址 z-reader/src/reader/driver/biquge/index.ts，访问笔趣阁官网获取
> > 3. 本地编译 yarn run build
> > 4. 安装本地打包生成的vslx文件
> 
> The engine "vscode" appears to be invalid
> 
> > 以笔趣阁为例
> > 
> > 1. 拉代码，安装依赖 yanr
> > 2. 修改本地请求地址 z-reader/src/reader/driver/biquge/index.ts，访问笔趣阁官网获取
> > 3. 本地编译 yarn run build
> > 4. 安装本地打包生成的vslx文件
> 
> ![image](https://user-images.githubusercontent.com/23521135/170216787-56ae6dc7-49ee-4066-988f-73cc829eb30f.png) 这怎么解决啊


试试修改 `tsconfig.json`

```diff
{
  "compilerOptions": {
    "forceConsistentCasingInFileNames": true,
    "experimentalDecorators": true,
    "module": "commonjs",
    "target": "es6",
    "outDir": "out",
-    "lib": ["es6"],
+    "lib": ["es6", "DOM"],
```

**Comment by maginapp** [comment]
拉起到的文本是gbk编码的，可以转化下

![image](https://user-images.githubusercontent.com/22275933/170241039-4d14f0b0-cb44-482d-8c01-9c4f1a3e38b4.png)


gbk使用的[gbk](https://github.com/cnwhy/GBK.js/tree/master/dist)，修改下代码，添加ts忽略

![image](https://user-images.githubusercontent.com/22275933/170241676-bd787c1d-d20b-49b9-ba47-e05aa1ba268d.png)

**Comment by Power-kxLee** [comment]
我尝试过删掉node_modules 
然后重装安装node_modules ，都提示全部安装完毕
我怀疑项目的`package.json` 是不是不完整呢？
现在编译的时候 还是 报错


```js
> Executing task: npm run build <


> z-reader@1.1.3 build D:\hb\z-reader
> vsce package

Executing prepublish script 'npm run vscode:prepublish'...

> z-reader@1.1.3 vscode:prepublish D:\hb\z-reader
> npm run compile


> z-reader@1.1.3 compile D:\hb\z-reader
> tsc -p ./

 ERROR  Command failed: npm list --production --parseable --depth=99999 --loglevel=error
npm ERR! missing: cheerio@1.0.0-rc.11, required by z-reader@1.1.3
npm ERR! missing: epub@1.2.1, required by z-reader@1.1.3
npm ERR! missing: got@9.6.0, required by z-reader@1.1.3
npm ERR! missing: hpagent@0.1.2, required by z-reader@1.1.3
npm ERR! missing: iconv-lite@0.5.2, required by z-reader@1.1.3
npm ERR! missing: open@7.4.2, required by z-reader@1.1.3
npm ERR! missing: tough-cookie@4.0.0, required by z-reader@1.1.3
npm ERR! missing: tslib@2.4.0, required by z-reader@1.1.3
npm ERR! missing: cheerio-select@2.1.0, required by cheerio@1.0.0-rc.11
npm ERR! missing: dom-serializer@2.0.0, required by cheerio@1.0.0-rc.11
npm ERR! missing: domhandler@5.0.3, required by cheerio@1.0.0-rc.11
npm ERR! missing: domutils@3.0.1, required by cheerio@1.0.0-rc.11
npm ERR! missing: htmlparser2@8.0.1, required by cheerio@1.0.0-rc.11
npm ERR! missing: parse5@7.0.0, required by cheerio@1.0.0-rc.11
npm ERR! missing: parse5-htmlparser2-tree-adapter@7.0.0, required by cheerio@1.0.0-rc.11
npm ERR! missing: tslib@2.4.0, required by cheerio@1.0.0-rc.11
npm ERR! missing: boolbase@1.0.0, required by cheerio-select@2.1.0
npm ERR! missing: css-select@5.1.0, required by cheerio-select@2.1.0
npm ERR! missing: css-what@6.1.0, required by cheerio-select@2.1.0
npm ERR! missing: domelementtype@2.3.0, required by cheerio-select@2.1.0
npm ERR! missing: domhandler@5.0.3, required by cheerio-select@2.1.0
npm ERR! missing: domutils@3.0.1, required by cheerio-select@2.1.0
npm ERR! missing: boolbase@1.0.0, required by css-select@5.1.0
npm ERR! missing: css-what@6.1.0, required by css-select@5.1.0
npm ERR! missing: domhandler@5.0.3, required by css-select@5.1.0
npm ERR! missing: domutils@3.0.1, required by css-select@5.1.0
npm ERR! missing: nth-check@2.1.1, required by css-select@5.1.0
npm ERR! missing: boolbase@1.0.0, required by nth-check@2.1.1
npm ERR! missing: domelementtype@2.3.0, required by dom-serializer@2.0.0
npm ERR! missing: domhandler@5.0.3, required by dom-serializer@2.0.0
npm ERR! missing: entities@4.3.0, required by dom-serializer@2.0.0
npm ERR! missing: domelementtype@2.3.0, required by domhandler@5.0.3
npm ERR! missing: dom-serializer@2.0.0, required by domutils@3.0.1
npm ERR! missing: domelementtype@2.3.0, required by domutils@3.0.1
npm ERR! missing: domhandler@5.0.3, required by domutils@3.0.1
npm ERR! missing: domelementtype@2.3.0, required by htmlparser2@8.0.1
npm ERR! missing: domhandler@5.0.3, required by htmlparser2@8.0.1
npm ERR! missing: domutils@3.0.1, required by htmlparser2@8.0.1
npm ERR! missing: entities@4.3.0, required by htmlparser2@8.0.1
npm ERR! missing: entities@4.3.0, required by parse5@7.0.0
npm ERR! missing: domhandler@5.0.3, required by parse5-htmlparser2-tree-adapter@7.0.0
npm ERR! missing: parse5@7.0.0, required by parse5-htmlparser2-tree-adapter@7.0.0
npm ERR! missing: adm-zip@0.4.16, required by epub@1.2.1
npm ERR! missing: xml2js@0.4.23, required by epub@1.2.1
npm ERR! missing: sax@1.2.4, required by xml2js@0.4.23
npm ERR! missing: xmlbuilder@11.0.1, required by xml2js@0.4.23
npm ERR! missing: mkdirp@0.5.6, required by node-pre-gyp@0.10.3
npm ERR! missing: rimraf@2.7.1, required by node-pre-gyp@0.10.3
npm ERR! missing: semver@5.7.1, required by node-pre-gyp@0.10.3
npm ERR! missing: minimist@1.2.6, required by mkdirp@0.5.6
npm ERR! missing: sax@1.2.4, required by needle@2.9.1
npm ERR! missing: safer-buffer@2.1.2, required by iconv-lite@0.4.24
npm ERR! missing: minimatch@3.1.2, required by ignore-walk@3.0.4
npm ERR! missing: brace-expansion@1.1.11, required by minimatch@3.1.2
npm ERR! missing: balanced-match@1.0.2, required by brace-expansion@1.1.11
npm ERR! missing: concat-map@0.0.1, required by brace-expansion@1.1.11
npm ERR! missing: set-blocking@2.0.0, required by npmlog@4.1.2
npm ERR! missing: readable-stream@2.3.7, required by are-we-there-yet@1.1.7
npm ERR! missing: core-util-is@1.0.3, required by readable-stream@2.3.7
npm ERR! missing: inherits@2.0.4, required by readable-stream@2.3.7
npm ERR! missing: isarray@1.0.0, required by readable-stream@2.3.7
npm ERR! missing: process-nextick-args@2.0.1, required by readable-stream@2.3.7
npm ERR! missing: safe-buffer@5.1.2, required by readable-stream@2.3.7
npm ERR! missing: string_decoder@1.1.1, required by readable-stream@2.3.7
npm ERR! missing: util-deprecate@1.0.2, required by readable-stream@2.3.7
npm ERR! missing: safe-buffer@5.1.2, required by string_decoder@1.1.1
npm ERR! missing: string-width@1.0.2, required by gauge@2.7.4
npm ERR! missing: strip-ansi@3.0.1, required by gauge@2.7.4
npm ERR! missing: code-point-at@1.1.0, required by string-width@1.0.2
npm ERR! missing: is-fullwidth-code-point@1.0.0, required by string-width@1.0.2
npm ERR! missing: strip-ansi@3.0.1, required by string-width@1.0.2
npm ERR! missing: number-is-nan@1.0.1, required by is-fullwidth-code-point@1.0.0
npm ERR! missing: ansi-regex@2.1.1, required by strip-ansi@3.0.1
npm ERR! missing: string-width@1.0.2, required by wide-align@1.1.5
npm ERR! missing: minimist@1.2.6, required by rc@1.2.8
npm ERR! missing: strip-json-comments@2.0.1, required by rc@1.2.8
npm ERR! missing: glob@7.2.0, required by rimraf@2.7.1
npm ERR! missing: fs.realpath@1.0.0, required by glob@7.2.0
npm ERR! missing: inflight@1.0.6, required by glob@7.2.0
npm ERR! missing: inherits@2.0.4, required by glob@7.2.0
npm ERR! missing: minimatch@3.1.2, required by glob@7.2.0
npm ERR! missing: once@1.4.0, required by glob@7.2.0
npm ERR! missing: path-is-absolute@1.0.1, required by glob@7.2.0
npm ERR! missing: once@1.4.0, required by inflight@1.0.6
npm ERR! missing: wrappy@1.0.2, required by inflight@1.0.6
npm ERR! missing: mkdirp@0.5.6, required by tar@4.4.19
npm ERR! missing: safe-buffer@5.1.2, required by minipass@2.9.0
npm ERR! missing: @sindresorhus/is@0.14.0, required by got@9.6.0
npm ERR! missing: @szmarczak/http-timer@1.1.2, required by got@9.6.0
npm ERR! missing: cacheable-request@6.1.0, required by got@9.6.0
npm ERR! missing: decompress-response@3.3.0, required by got@9.6.0
npm ERR! missing: duplexer3@0.1.4, required by got@9.6.0
npm ERR! missing: get-stream@4.1.0, required by got@9.6.0
npm ERR! missing: lowercase-keys@1.0.1, required by got@9.6.0
npm ERR! missing: mimic-response@1.0.1, required by got@9.6.0
npm ERR! missing: p-cancelable@1.1.0, required by got@9.6.0
npm ERR! missing: to-readable-stream@1.0.0, required by got@9.6.0
npm ERR! missing: url-parse-lax@3.0.0, required by got@9.6.0
npm ERR! missing: defer-to-connect@1.1.3, required by @szmarczak/http-timer@1.1.2
npm ERR! missing: get-stream@5.2.0, required by cacheable-request@6.1.0
npm ERR! missing: lowercase-keys@2.0.0, required by cacheable-request@6.1.0
npm ERR! missing: clone-response@1.0.2, required by cacheable-request@6.1.0
npm ERR! missing: http-cache-semantics@4.1.0, required by cacheable-request@6.1.0
npm ERR! missing: keyv@3.1.0, required by cacheable-request@6.1.0
npm ERR! missing: normalize-url@4.5.1, required by cacheable-request@6.1.0
npm ERR! missing: responselike@1.0.2, required by cacheable-request@6.1.0
npm ERR! missing: pump@3.0.0, required by get-stream@5.2.0
npm ERR! missing: mimic-response@1.0.1, required by clone-response@1.0.2
npm ERR! missing: json-buffer@3.0.0, required by keyv@3.1.0
npm ERR! missing: lowercase-keys@1.0.1, required by responselike@1.0.2
npm ERR! missing: mimic-response@1.0.1, required by decompress-response@3.3.0
npm ERR! missing: pump@3.0.0, required by get-stream@4.1.0
npm ERR! missing: end-of-stream@1.4.4, required by pump@3.0.0
npm ERR! missing: once@1.4.0, required by pump@3.0.0
npm ERR! missing: once@1.4.0, required by end-of-stream@1.4.4
npm ERR! missing: wrappy@1.0.2, required by once@1.4.0
npm ERR! missing: prepend-http@2.0.0, required by url-parse-lax@3.0.0
npm ERR! missing: safer-buffer@2.1.2, required by iconv-lite@0.5.2
npm ERR! missing: is-docker@2.2.1, required by open@7.4.2
npm ERR! missing: is-wsl@2.2.0, required by open@7.4.2
npm ERR! missing: is-docker@2.2.1, required by is-wsl@2.2.0
npm ERR! missing: psl@1.8.0, required by tough-cookie@4.0.0
npm ERR! missing: punycode@2.1.1, required by tough-cookie@4.0.0
npm ERR! missing: universalify@0.1.2, required by tough-cookie@4.0.0

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! z-reader@1.1.3 build: `vsce package`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the z-reader@1.1.3 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\MyData\ex_likx5\AppData\Roaming\npm-cache\_logs\2022-05-26T02_02_50_769Z-debug.log
终端进程“C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -Command npm run build”已终止，退出代码: 1。
```

**Comment by Power-kxLee** [comment]
> [aooiuu](/aooiuu)

**Comment by Power-kxLee** [comment]
> 我尝试过删掉node_modules 然后重装安装node_modules ，都提示全部安装完毕 我怀疑项目的`package.json` 是不是不完整呢？ 现在编译的时候 还是 报错
> 
> ```js
> > Executing task: npm run build <
> 
> 
> > z-reader@1.1.3 build D:\hb\z-reader
> > vsce package
> 
> Executing prepublish script 'npm run vscode:prepublish'...
> 
> > z-reader@1.1.3 vscode:prepublish D:\hb\z-reader
> > npm run compile
> 
> 
> > z-reader@1.1.3 compile D:\hb\z-reader
> > tsc -p ./
> 
>  ERROR  Command failed: npm list --production --parseable --depth=99999 --loglevel=error
> npm ERR! missing: cheerio@1.0.0-rc.11, required by z-reader@1.1.3
> npm ERR! missing: epub@1.2.1, required by z-reader@1.1.3
> npm ERR! missing: got@9.6.0, required by z-reader@1.1.3
> npm ERR! missing: hpagent@0.1.2, required by z-reader@1.1.3
> npm ERR! missing: iconv-lite@0.5.2, required by z-reader@1.1.3
> npm ERR! missing: open@7.4.2, required by z-reader@1.1.3
> npm ERR! missing: tough-cookie@4.0.0, required by z-reader@1.1.3
> npm ERR! missing: tslib@2.4.0, required by z-reader@1.1.3
> npm ERR! missing: cheerio-select@2.1.0, required by cheerio@1.0.0-rc.11
> npm ERR! missing: dom-serializer@2.0.0, required by cheerio@1.0.0-rc.11
> npm ERR! missing: domhandler@5.0.3, required by cheerio@1.0.0-rc.11
> npm ERR! missing: domutils@3.0.1, required by cheerio@1.0.0-rc.11
> npm ERR! missing: htmlparser2@8.0.1, required by cheerio@1.0.0-rc.11
> npm ERR! missing: parse5@7.0.0, required by cheerio@1.0.0-rc.11
> npm ERR! missing: parse5-htmlparser2-tree-adapter@7.0.0, required by cheerio@1.0.0-rc.11
> npm ERR! missing: tslib@2.4.0, required by cheerio@1.0.0-rc.11
> npm ERR! missing: boolbase@1.0.0, required by cheerio-select@2.1.0
> npm ERR! missing: css-select@5.1.0, required by cheerio-select@2.1.0
> npm ERR! missing: css-what@6.1.0, required by cheerio-select@2.1.0
> npm ERR! missing: domelementtype@2.3.0, required by cheerio-select@2.1.0
> npm ERR! missing: domhandler@5.0.3, required by cheerio-select@2.1.0
> npm ERR! missing: domutils@3.0.1, required by cheerio-select@2.1.0
> npm ERR! missing: boolbase@1.0.0, required by css-select@5.1.0
> npm ERR! missing: css-what@6.1.0, required by css-select@5.1.0
> npm ERR! missing: domhandler@5.0.3, required by css-select@5.1.0
> npm ERR! missing: domutils@3.0.1, required by css-select@5.1.0
> npm ERR! missing: nth-check@2.1.1, required by css-select@5.1.0
> npm ERR! missing: boolbase@1.0.0, required by nth-check@2.1.1
> npm ERR! missing: domelementtype@2.3.0, required by dom-serializer@2.0.0
> npm ERR! missing: domhandler@5.0.3, required by dom-serializer@2.0.0
> npm ERR! missing: entities@4.3.0, required by dom-serializer@2.0.0
> npm ERR! missing: domelementtype@2.3.0, required by domhandler@5.0.3
> npm ERR! missing: dom-serializer@2.0.0, required by domutils@3.0.1
> npm ERR! missing: domelementtype@2.3.0, required by domutils@3.0.1
> npm ERR! missing: domhandler@5.0.3, required by domutils@3.0.1
> npm ERR! missing: domelementtype@2.3.0, required by htmlparser2@8.0.1
> npm ERR! missing: domhandler@5.0.3, required by htmlparser2@8.0.1
> npm ERR! missing: domutils@3.0.1, required by htmlparser2@8.0.1
> npm ERR! missing: entities@4.3.0, required by htmlparser2@8.0.1
> npm ERR! missing: entities@4.3.0, required by parse5@7.0.0
> npm ERR! missing: domhandler@5.0.3, required by parse5-htmlparser2-tree-adapter@7.0.0
> npm ERR! missing: parse5@7.0.0, required by parse5-htmlparser2-tree-adapter@7.0.0
> npm ERR! missing: adm-zip@0.4.16, required by epub@1.2.1
> npm ERR! missing: xml2js@0.4.23, required by epub@1.2.1
> npm ERR! missing: sax@1.2.4, required by xml2js@0.4.23
> npm ERR! missing: xmlbuilder@11.0.1, required by xml2js@0.4.23
> npm ERR! missing: mkdirp@0.5.6, required by node-pre-gyp@0.10.3
> npm ERR! missing: rimraf@2.7.1, required by node-pre-gyp@0.10.3
> npm ERR! missing: semver@5.7.1, required by node-pre-gyp@0.10.3
> npm ERR! missing: minimist@1.2.6, required by mkdirp@0.5.6
> npm ERR! missing: sax@1.2.4, required by needle@2.9.1
> npm ERR! missing: safer-buffer@2.1.2, required by iconv-lite@0.4.24
> npm ERR! missing: minimatch@3.1.2, required by ignore-walk@3.0.4
> npm ERR! missing: brace-expansion@1.1.11, required by minimatch@3.1.2
> npm ERR! missing: balanced-match@1.0.2, required by brace-expansion@1.1.11
> npm ERR! missing: concat-map@0.0.1, required by brace-expansion@1.1.11
> npm ERR! missing: set-blocking@2.0.0, required by npmlog@4.1.2
> npm ERR! missing: readable-stream@2.3.7, required by are-we-there-yet@1.1.7
> npm ERR! missing: core-util-is@1.0.3, required by readable-stream@2.3.7
> npm ERR! missing: inherits@2.0.4, required by readable-stream@2.3.7
> npm ERR! missing: isarray@1.0.0, required by readable-stream@2.3.7
> npm ERR! missing: process-nextick-args@2.0.1, required by readable-stream@2.3.7
> npm ERR! missing: safe-buffer@5.1.2, required by readable-stream@2.3.7
> npm ERR! missing: string_decoder@1.1.1, required by readable-stream@2.3.7
> npm ERR! missing: util-deprecate@1.0.2, required by readable-stream@2.3.7
> npm ERR! missing: safe-buffer@5.1.2, required by string_decoder@1.1.1
> npm ERR! missing: string-width@1.0.2, required by gauge@2.7.4
> npm ERR! missing: strip-ansi@3.0.1, required by gauge@2.7.4
> npm ERR! missing: code-point-at@1.1.0, required by string-width@1.0.2
> npm ERR! missing: is-fullwidth-code-point@1.0.0, required by string-width@1.0.2
> npm ERR! missing: strip-ansi@3.0.1, required by string-width@1.0.2
> npm ERR! missing: number-is-nan@1.0.1, required by is-fullwidth-code-point@1.0.0
> npm ERR! missing: ansi-regex@2.1.1, required by strip-ansi@3.0.1
> npm ERR! missing: string-width@1.0.2, required by wide-align@1.1.5
> npm ERR! missing: minimist@1.2.6, required by rc@1.2.8
> npm ERR! missing: strip-json-comments@2.0.1, required by rc@1.2.8
> npm ERR! missing: glob@7.2.0, required by rimraf@2.7.1
> npm ERR! missing: fs.realpath@1.0.0, required by glob@7.2.0
> npm ERR! missing: inflight@1.0.6, required by glob@7.2.0
> npm ERR! missing: inherits@2.0.4, required by glob@7.2.0
> npm ERR! missing: minimatch@3.1.2, required by glob@7.2.0
> npm ERR! missing: once@1.4.0, required by glob@7.2.0
> npm ERR! missing: path-is-absolute@1.0.1, required by glob@7.2.0
> npm ERR! missing: once@1.4.0, required by inflight@1.0.6
> npm ERR! missing: wrappy@1.0.2, required by inflight@1.0.6
> npm ERR! missing: mkdirp@0.5.6, required by tar@4.4.19
> npm ERR! missing: safe-buffer@5.1.2, required by minipass@2.9.0
> npm ERR! missing: @sindresorhus/is@0.14.0, required by got@9.6.0
> npm ERR! missing: @szmarczak/http-timer@1.1.2, required by got@9.6.0
> npm ERR! missing: cacheable-request@6.1.0, required by got@9.6.0
> npm ERR! missing: decompress-response@3.3.0, required by got@9.6.0
> npm ERR! missing: duplexer3@0.1.4, required by got@9.6.0
> npm ERR! missing: get-stream@4.1.0, required by got@9.6.0
> npm ERR! missing: lowercase-keys@1.0.1, required by got@9.6.0
> npm ERR! missing: mimic-response@1.0.1, required by got@9.6.0
> npm ERR! missing: p-cancelable@1.1.0, required by got@9.6.0
> npm ERR! missing: to-readable-stream@1.0.0, required by got@9.6.0
> npm ERR! missing: url-parse-lax@3.0.0, required by got@9.6.0
> npm ERR! missing: defer-to-connect@1.1.3, required by @szmarczak/http-timer@1.1.2
> npm ERR! missing: get-stream@5.2.0, required by cacheable-request@6.1.0
> npm ERR! missing: lowercase-keys@2.0.0, required by cacheable-request@6.1.0
> npm ERR! missing: clone-response@1.0.2, required by cacheable-request@6.1.0
> npm ERR! missing: http-cache-semantics@4.1.0, required by cacheable-request@6.1.0
> npm ERR! missing: keyv@3.1.0, required by cacheable-request@6.1.0
> npm ERR! missing: normalize-url@4.5.1, required by cacheable-request@6.1.0
> npm ERR! missing: responselike@1.0.2, required by cacheable-request@6.1.0
> npm ERR! missing: pump@3.0.0, required by get-stream@5.2.0
> npm ERR! missing: mimic-response@1.0.1, required by clone-response@1.0.2
> npm ERR! missing: json-buffer@3.0.0, required by keyv@3.1.0
> npm ERR! missing: lowercase-keys@1.0.1, required by responselike@1.0.2
> npm ERR! missing: mimic-response@1.0.1, required by decompress-response@3.3.0
> npm ERR! missing: pump@3.0.0, required by get-stream@4.1.0
> npm ERR! missing: end-of-stream@1.4.4, required by pump@3.0.0
> npm ERR! missing: once@1.4.0, required by pump@3.0.0
> npm ERR! missing: once@1.4.0, required by end-of-stream@1.4.4
> npm ERR! missing: wrappy@1.0.2, required by once@1.4.0
> npm ERR! missing: prepend-http@2.0.0, required by url-parse-lax@3.0.0
> npm ERR! missing: safer-buffer@2.1.2, required by iconv-lite@0.5.2
> npm ERR! missing: is-docker@2.2.1, required by open@7.4.2
> npm ERR! missing: is-wsl@2.2.0, required by open@7.4.2
> npm ERR! missing: is-docker@2.2.1, required by is-wsl@2.2.0
> npm ERR! missing: psl@1.8.0, required by tough-cookie@4.0.0
> npm ERR! missing: punycode@2.1.1, required by tough-cookie@4.0.0
> npm ERR! missing: universalify@0.1.2, required by tough-cookie@4.0.0
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! z-reader@1.1.3 build: `vsce package`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the z-reader@1.1.3 build script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     D:\MyData\ex_likx5\AppData\Roaming\npm-cache\_logs\2022-05-26T02_02_50_769Z-debug.log
> 终端进程“C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -Command npm run build”已终止，退出代码: 1。
> ```

我又检测了一下安装包 
```js
cnpm install
√ Installed 22 packages
√ Linked 0 latest versions
√ Run 0 scripts
√ All packages installed (used 32ms(network 26ms), speed 0B/s, json 0(0B), tarball 0B, manifests cache hit 0, etag hit 0 / miss 0)
```

**Comment by Power-kxLee** [comment]
应该是node版本问题了 我试试升级

**Comment by aooiuu** [comment]
> ```js
> ERROR  Command failed: npm list --production --parseable --depth=99999 --loglevel=error
> ```

https://github.com/microsoft/vscode-vsce/issues/477

**Comment by aooiuu** [comment]
> 应该是node版本问题了 我试试升级

用 yarn 试试， vscode 仓库有类似的 issues

**Comment by 1061706503** [comment]
新的笔趣阁搜索地址是多少呢

**Comment by 1061706503** [comment]
现在搜索报403
