### ISSUE TITLE
起点添加cookie无效

### ISSUE THREAD

**Issue by EaxMov** [aooiuu/z-reader#83]
"z-reader.cookies": [
    {
      "url": "https://m.qidian.com",
      "cookie": “a=xx;b=xx"
    }
  ]

无效，cookie从https://m.qidian.com登录复制的。

**Comment by aooiuu** [comment]
试一下 `重新加载cookie设置` 插件目前没有监听配置更新事件

**Comment by EaxMov** [comment]
一样啊，还是无效
    {
      "url": "m.qidian.com",
      "cookie": "newstatisticUUID=1652682127_1790907442; 
    }
不带http也不行

**Comment by aooiuu** [comment]
> 一样啊，还是无效 { "url": "m.qidian.com", "cookie": "newstatisticUUID=1652682127_1790907442; } 不带http也不行


复制完整cookie试试, 网站提交什么cookie就复制什么cookie, 我这边 windows 和 wsl 都测试正常

使用cookie的代码其实很简单: https://github.com/aooiuu/z-reader/blob/master/src/utils/request.ts

也可以自行抓包或调试看看

**Comment by aooiuu** [comment]
https://github.com/aooiuu/z-reader/issues/90

**Comment by aooiuu** [comment]
#90
