### ISSUE TITLE
z-reader，当源是：笔趣阁.

### ISSUE THREAD

**Issue by colaQAQz** [aooiuu/z-reader#89]
搜索小说会显示：读取目录失败，请检测您的目录设置

**Comment by colaQAQz** [comment]
搜索不会显示小说，换成起点就可以...

**Comment by odomodo** [comment]
是笔趣阁的源用不了吗，搜索目录为空，起点就很正常，但是看不了盗版了

**Comment by colaQAQz** [comment]
是的，源是笔趣阁不行，起点就可以，可能笔趣阁源被封了....但是手机笔趣阁没问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月15日(星期三) 下午3:12
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [aooiuu/z-reader] z-reader，当源是：笔趣阁. (Issue #89)





 
是笔趣阁的源用不了吗，搜索目录为空，起点就很正常，但是看不了盗版了

**Comment by colaQAQz** [comment]
可惜了 唉



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月16日(星期四) 下午3:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [aooiuu/z-reader] z-reader，当源是：笔趣阁. (Issue #89)





 
是因为里面的php接口返回的东西变了，代码里用classname取dom拿不到了，感觉工作量不小，估计不打算改了

**Comment by deadeveryou** [comment]
> 可惜了 唉
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年6月16日(星期四) 下午3:21 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [aooiuu/z-reader] z-reader，当源是：笔趣阁. (Issue #89) 是因为里面的php接口返回的东西变了，代码里用classname取dom拿不到了，感觉工作量不小，估计不打算改了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

主要是这个设计的时候就不好，不过也没办法，这个笔趣阁就是这样搞的，页面是后端写的，没办法

**Comment by myadmin** [comment]
提交了新的pr，更换了笔趣阁的地址，可以重新获取到内容了，需要作者合并一下发个新版。

**Comment by colaQAQz** [comment]
厉害👍，那希望作者能有时间合并一下！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月16日(星期四) 下午4:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [aooiuu/z-reader] z-reader，当源是：笔趣阁. (Issue #89)





 
提交了新的pr，更换了笔趣阁的地址，可以重新获取到内容了，需要作者合并一下发个新版。

**Comment by colaQAQz** [comment]
好的，过两天就可以继续看小说了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月16日(星期四) 下午5:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [aooiuu/z-reader] z-reader，当源是：笔趣阁. (Issue #89)






感谢，晚上发版哦

—
直接回复此邮件，在 GitHub 上查看或取消订阅.
您收到这个消息是因为您编写了这个线程。留言 ID ***@***.***与&gt;

**Comment by aooiuu** [comment]
https://github.com/aooiuu/z-reader/pull/91
