### ISSUE TITLE
起点的小说无法查看

### ISSUE THREAD

**Issue by trangles** [aooiuu/z-reader#90]
- version:  1.1.5

按照设置 我去m.qidian.com登录后在控制台用

> document.cookie

抓到了当前使用的cookie,将其添加至setting.json中
```
    "z-reader.cookies": [
        {
          "url": "https://m.qidian.com",
          "cookie": ""
        }
      ],
```

然后订阅章节显示

> 上起点读书APP支持我 还可在评论区与我互动

此外，尚未订阅的章节会显示部分内容和当前章节所需起点币及剩余起点币，但只要一订阅就只显示上面这句话了>_<

**Comment by ShaunVyxw** [comment]
version 1.1.7
配置cookie后，付费章节显示如下：
我在起点读书APP创作
欢迎来支持正版

**Comment by mushisan3333** [comment]
+1
