### ISSUE TITLE
应该怎样调整段落间距？

### ISSUE THREAD

**Issue by sunkr1995** [aooiuu/z-reader#96]
我尝试在style.css 上 的 content 中加入padding Margin、Border 都没有达到想要的结果。
一个css、html小白诚恳的提问。。。

**Comment by mantis3d** [comment]
调整 line-height，应该是在第35行。

**Comment by sunkr1995** [comment]
> 调整 line-height，应该是在第35行。

line-height是行间距啊，我想调整的是段落间距

**Comment by PlayerYao** [comment]
在样式里加入
```
.content>p,
.content>div{
  margin: -4px 0px;
 /* 第一个是上下间距, 负数就是减小 第二个是左右边距 */
}
```

**Comment by aooiuu** [comment]
https://github.com/aooiuu/any-reader

建议使用新插件。新插件有这个功能
